apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: practice
  name: practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice
  strategy: {}
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
