apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app.kubernetes.io/part-of: autodeploy
    app.kubernetes.io/managed-by: argocd
  namespace: demo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.3
    path: /srv/nfs/shared/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
