apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: demo-app
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.3
    path: /srv/nfs/shared/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: demo-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
