# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: redis-pv
#   labels:
#     app.kubernetes.io/part-of: autodeploy
#     app.kubernetes.io/managed-by: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
#   namespace: demo-app
# spec:
#   capacity:
#     storage: 500Mi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     server: 192.168.56.3
#     path: /srv/nfs/shared/redis
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
#   namespace: demo-app
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 500Mi
