name: Docker Compose CI

on:
  push:
    branches: [main]

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and run containers
        run: |
          cd docker-project
          docker-compose down --volumes --remove-orphans
          docker-compose build --no-cache

